SELECT
    ALU.NOME
FROM TURMA TUR
INNER JOIN ALUNO_TURMA ATU ON ATU.ALUNO_ID = TUR.ALUNO_ID
INNER JOIN ALUNO ALU ON ALU.ID = ATU.ALUNO_ID
INNER JOIN PROFESSOR PRO ON PRO.ID = TUR.ALUNO_ID
WHERE PRO.NOME = "JOAO PEDRO"


SELECT
    TUR.DIAS_DA_SEMANA,
FROM TURMA TUR
INNER JOIN DISCIPLINA DIS ON DIS.ID = TUR.DISCIPLINA_ID
WHERE DIS.NOME = "MATEMATICA"


SELECT
    ALU.NOME
FROM TURMA TUR
INNER JOIN DISCIPLINA DIS ON DIS.ID = TUR.DISCIPLINA_ID
INNER JOIN ALUNO_TURMA ATU ON ATU.ALUNO_ID = TUR.ALUNO_ID
INNER JOIN ALUNO ALU ON ALU.ID = ATU.ALUNO_ID
WHERE DIS.NOME IN ("MATEMATICA", "FISICA")


SELECT
    DIS.NOME
FROM DISCIPLINA DIS
LEFT JOIN TURMA TUR ON TUR.DISCIPLINA_ID = DIS.ID
WHERE TUR.DISCIPLINA_ID IS NULL


WITH ALUNO_DIS AS (
    SELECT
        DISCIPLINA.NOME AS DISCIPLINA_NOME,
        ALU.ID
    FROM TURMA TUR
    INNER JOIN DISCIPLINA DIS ON TUR.DISCIPLINA_ID = DIS.ID
    INNER JOIN ALUNO_TURMA ATUR ON ATUR.ALUNO_ID = TUR.ALUNO_ID
    INNER JOIN ALUNO ALU ON ALU.COD = ATUR.ALUNO_ID
)
SELECT 
    ALU.NOME
FROM ALUNO ALU
WHERE ALU.ID IN (SELECT ID FROM ALUNO_DIS WHERE DISCIPLINA_NOME = "MATIMATICA") AND
      ALU.ID NOT IN (SELECT ID FROM ALUNO_DIS WHERE DISCIPLINA_NOME = "QUIMICA")

